### ISSUE TITLE
Online ide?

### ISSUE THREAD

**Issue by BasToTheMax** [customrealms/core#2]
Before the open source version of custom realms, there was an online IDE (with hosting). Will this come back or will there be a new version of the IDE or will there be no online IDE?

**Comment by connerdouglass** [comment]
I don't think there will be an online IDE. It was convenient, but the hosting was relatively costly.

What are your thoughts about it?

**Comment by BasToTheMax** [comment]
You could use Contabo to host the servers. Wich is around $1 per GB RAM!

( I also use Contabo for all my projects )

**Comment by connerdouglass** [comment]
Oh okay that's nice. I'll definitely consider it.

One thing I want to do is to add a command to the CLI, something like `crx devserver` which would automatically spin up a Spigot / Paper server on your computer and run your plugin, while you're coding it.

I think that would make it easy like the online IDE was.

**Comment by BasToTheMax** [comment]
Yeah. But some people don't know how to use NodeJS ect, but know how to use Custom Realmst (because before the open source version, they hadn't to bother about compiling ect (my English is not the best, but I hope you understand it))

**Comment by BasToTheMax** [comment]
We also could use AdinPlay, so users need to watch an ad to host their debug server ( for 60 minutes )

https://adinplay.com/ad-types/ and choose Reward Ads

**Comment by BasToTheMax** [comment]
When will you send the code of the frondend? So I can also start working on the backend!

**Comment by BasToTheMax** [comment]
I am going to make my own version of CustomRealms. This is dead.
