### ISSUE TITLE
Is there an error?

### ISSUE THREAD

**Issue by Selvoid** [customrealms/core#20]
So I was attempting to make it so if the block you are standing on is stone, you would launch into the sky but I went into a problem:
```ts
ServerEvents.register(PlayerMoveEvent, event => {
    const player = event.getPlayer();
    const block = event.getPlayer().getLocation().setY(-1);
    const stone = Block.name.match("Stone");
    if (!player) return;
    if (!stone) return;
    if (block == stone) player.setVelocity(new Vector(0, 10, 0));
});
```
It all doesn't work do you know why?

**Comment by AL1L** [comment]
Likely that that stone is null or undefined. You should use the Discord server for support, and only use GitHub issues, for issues.

**Comment by Selvoid** [comment]
ok thanks
