### ISSUE TITLE
Upload several plugins on the server

### ISSUE THREAD

**Issue by shanodis** [customrealms/core#35]
Is it possible to upload several plugins on the server? I mean e.g. two .jar files compiled with crx build command. Because right now I'm getting error from J2V8 while loading. When I'm loading one plugin everything works correctly
![unknown](https://user-images.githubusercontent.com/62188218/184634041-0a55c945-4e77-42ab-bd89-02e20bfd08dc.png)

**Comment by ANDREI12333** [comment]
It is probably a bug.

**Comment by ghost** [comment]
The plugins probably have the same v8 classes.

**Comment by ghost** [comment]
Which that's by default a problem

**Comment by connerdouglass** [comment]
This bug has been fixed in V2 of CustomRealms.
